version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: APSUNIP
      MONGO_INITDB_ROOT_PASSWORD: APSUNIP
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
